export const ru = {
  app: {
    name: 'WikiWeaver',
    description: 'ваша платформа для создания и управления wiki-контентом',
  },
  layout: {
    menu: {
      home: 'Главная',
      addArticle: 'Добавить статью',
      admin: 'Панель администратора',
    },
    actions: {
      adminPanel: 'Админ панель',
      logout: 'Выйти',
    },
    navigation: {
      open: 'Открыть панель навигации',
      close: 'Закрыть панель навигации',
      searchPlaceholder: 'Поиск',
    },
  },
  common: {
    unknownError: 'Неизвестная ошибка',
    delete: 'Удалить',
    actions: 'Действия',
    id: 'ID',
    title: 'Название',
    save: 'Сохранить',
    settings: 'Настройки',
    data: 'Данные',
  },
  welcomePage: {
    title: 'Добро пожаловать в WikiWeaver',
    selectArticleMessage: 'Выберите статью в панели навигации слева, чтобы начать.',
  },
  articlePage: {
    previousAlternative: 'Предыдущая альтернатива',
    nextAlternative: 'Следующая альтернатива',
    noContent: 'Нет доступного контента',
    articleNotFound: 'Статья не найдена',
    loadError: 'Ошибка загрузки статьи',
    uiModeUpdated: 'Режим отображения абзацев обновлён',
  },
  addArticlePage: {
    title: 'Новая статья',
    saved: 'Статья сохранена',
    saveError: 'Ошибка сохранения',
    modelTitle: 'Модель хранения',
    modelDescription:
      'Каждый абзац — это группа альтернатив. Можно сохранить только основную версию, а альтернативы добавить позже, либо сразу создать несколько версий в одном порядке.',
    articleTitlePlaceholder: 'Заголовок статьи',
    parentArticleIdPlaceholder: 'ID родительской статьи (необязательно)',
    importDraft: 'Импортировать черновик Markdown',
    improveAllAi: 'Улучшить стиль с помощью ИИ',
    paragraphStats: 'Абзацев',
    versionsStats: 'Версий',
    paragraphTitle: 'Абзац',
    addAlternative: 'Добавить альтернативу',
    version: 'Версия',
    defaultLabel: 'По умолчанию',
    aiStyle: 'ИИ-стиль',
    remove: 'Удалить',
    editorPlaceholder: 'Напишите версию абзаца в Markdown',
    addParagraph: 'Добавить абзац',
    saveArticle: 'Сохранить статью',
    importModalTitle: 'Импортировать черновик Markdown',
    importButton: 'Импортировать',
    importHint: 'Разделяйте абзацы пустой строкой. Импорт создаст по одной версии на каждый абзац.',
    importPlaceholder: 'Абзац 1\n\nАбзац 2\n\nАбзац 3',
    toolbarHint: 'Панель форматирования общая для всей статьи. Выберите абзац и применяйте инструменты.',
    warnings: {
      selectParagraphForFormatting: 'Выберите абзац, который нужно отформатировать',
      noParagraphsForAi: 'Нет заполненных абзацев для стилизации',
      titleRequired: 'Укажите заголовок статьи',
      paragraphRequired: 'Добавьте хотя бы один заполненный абзац',
      defaultRequired: 'Для каждого абзаца должна быть заполнена хотя бы одна версия по умолчанию',
      importEmpty: 'Не найдено абзацев для импорта',
    },
    aiStyledParagraph: 'Абзац стилизован',
    aiStyleFailed: 'ИИ-стилизация не выполнена',
    styledVersions: 'Стилизовано версий',
    importedParagraphs: 'Импортировано абзацев',
  },
  adminPage: {
    title: 'Панель администратора (MVP)',
    temporaryAccessTitle: 'Временный открытый доступ',
    temporaryAccessDescription:
      'Эта админ-панель временно публична для MVP. Ограничение доступа (аутентификация/роли) будет добавлено в следующей итерации.',
    contentTab: 'Контент',
    searchPlaceholder: 'Поиск по id/названию/контенту',
    articlesTab: 'Статьи',
    paragraphsTab: 'Абзацы',
    cleanupTab: 'Очистка демо-данных',
    deleteAll: 'Удалить все статьи',
    parentId: 'ID родителя',
    root: 'корень',
    articleDeleted: 'Статья удалена',
    paragraphDeleted: 'Абзац удалён',
    deleteArticle: 'Удалить статью',
    deleteParagraph: 'Удалить абзац',
    articleDeleteFailed: 'Не удалось удалить статью',
    paragraphDeleteFailed: 'Не удалось удалить абзац',
    cleanupDone: 'Очистка завершена. Удалено статей: {articles}, абзацев: {paragraphs}.',
    cleanupFailed: 'Не удалось очистить демо-данные',
    cleanupModalTitle: 'Удалить все демо-данные',
    cleanupModalOk: 'Удалить всё',
    cleanupModalHint: 'Введите {phrase}, чтобы подтвердить безвозвратное удаление всех статей и абзацев.',
    cleanupConfirmationPhrase: 'DELETE DEMO DATA',
    aiTab: 'ИИ',
    uiTab: 'Интерфейс',
    aiDisabledHint: 'Если выключено (серый), ИИ-стилизация отключена в приложении, а поля конфигурации ниже блокируются.',
    baseUrl: 'Base URL',
    model: 'Модель',
    apiKey: 'API key',
    baseUrlRequired: 'Base URL обязателен',
    modelRequired: 'Модель обязательна',
    apiKeyHint: 'Оставьте пустым при обычном сохранении, чтобы сохранить текущий ключ без изменений.',
    apiConfigured: 'Настроен',
    baseUrlPlaceholder: 'https://api.openai.com/v1',
    modelPlaceholder: 'gpt-4o-mini',
    apiKeyPlaceholder: 'sk-...',
    saveAiSettings: 'Сохранить настройки ИИ',
    deleteApiKey: 'Удалить текущий API key',
    checkAiConnection: 'Проверить подключение ИИ',
    aiSettingsUpdated: 'Настройки ИИ обновлены',
    aiSettingsUpdateFailed: 'Не удалось обновить настройки ИИ',
    aiCheckResultTitle: 'Результат проверки ИИ',
    aiModelExample: 'Пример ответа модели:',
    aiCheckFailed: 'Проверка ИИ не пройдена',
    apiKeyDeleted: 'Текущий API key удалён из настроек',
    uiModeArrows: 'Стрелки (карусель)',
    uiModeNumbers: 'Рамка + номера',
    articleId: 'ID статьи',
    order: 'Порядок',
    content: 'Контент',
    inviteTokenTitle: 'Invite token для нового администратора',
    generateInviteToken: 'Сгенерировать invite token',
    inviteTokenGenerated: 'Invite token сгенерирован',
    inviteTokenGenerateFailed: 'Не удалось сгенерировать invite token',
    createArticleTab: 'Создание статьи',
    createArticleTitle: 'Создание новой статьи',
    createArticleDescription: 'Переход к форме создания статьи вынесен в отдельную вкладку админ-панели.',
    createArticleAction: 'Перейти к созданию статьи',
  },
  adminLoginPage: {
    loginSuccess: 'Сессия администратора начата',
    registerSuccess: 'Аккаунт администратора создан',
    registerTitle: 'Регистрация администратора',
    loginTitle: 'Вход администратора',
    emailLabel: 'Email',
    passwordLabel: 'Пароль',
    inviteTokenLabel: 'Invite token',
    firstAdminHint: 'Первый зарегистрировавшийся станет админом без invite token',
    registerAction: 'Зарегистрироваться',
    loginAction: 'Войти',
    haveAccount: 'У меня уже есть аккаунт',
    createAccount: 'Создать админ-аккаунт',
  },
  sidebar: {
    loadError: 'Ошибка загрузки навигации',
  },
  markdownEditor: {
    bold: 'Жирный',
    italic: 'Курсив',
    heading: 'H2',
    list: 'Список',
    quote: 'Цитата',
    insertText: 'текст',
    headingSnippet: 'Заголовок',
    listSnippet: 'Пункт',
    quoteSnippet: 'Цитата',
    lineCount: 'Строк Markdown',
  },
} as const;
