// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiWeaver.Infrastructure.Data;

#nullable disable

namespace WikiWeaver.Infrastructure.Migrations
{
    [DbContext(typeof(WikiWeaverDbContext))]
    [Migration("20260403200324_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WikiWeaver.Domain.Entities.AdminInviteToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsedByAdminId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsedByAdminId");

                    b.ToTable("AdminInviteTokens");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.AiProviderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkdownStylingSystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiProviderSettings");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentArticleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.AdminInviteToken", b =>
                {
                    b.HasOne("WikiWeaver.Domain.Entities.AdminUser", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WikiWeaver.Domain.Entities.AdminUser", "UsedByAdmin")
                        .WithMany()
                        .HasForeignKey("UsedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("UsedByAdmin");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.Article", b =>
                {
                    b.HasOne("WikiWeaver.Domain.Entities.Article", "ParentArticle")
                        .WithMany("ChildArticles")
                        .HasForeignKey("ParentArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentArticle");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.Paragraph", b =>
                {
                    b.HasOne("WikiWeaver.Domain.Entities.Article", "Article")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("WikiWeaver.Domain.Entities.Article", b =>
                {
                    b.Navigation("ChildArticles");

                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
